"""Dodanie kolumny e-mail do tabeli Candidates

Revision ID: 494c903e7e1c
Revises: 28f0b8b2ee55
Create Date: 2024-12-12 20:06:40.574465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '494c903e7e1c'
down_revision = '28f0b8b2ee55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_cv', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.drop_column('email_cv')

    # ### end Alembic commands ###
