"""Dodanie kolumny phone_number do tabeli Candidate

Revision ID: 5f9a7e140ee2
Revises: 494c903e7e1c
Create Date: 2024-12-12 20:33:41.633925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f9a7e140ee2'
down_revision = '494c903e7e1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
