"""Dodanie kolumny path do tabeli Candidate

Revision ID: 8b6020eae94e
Revises: 47a4814adba4
Create Date: 2024-12-13 23:42:04.053475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b6020eae94e'
down_revision = '47a4814adba4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    connection = op.get_bind()
    connection.execute(
        sa.text("UPDATE candidate SET user_id = 1 WHERE user_id IS NULL")
    )


    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.String(length=255), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('path')

    # ### end Alembic commands ###
